taskboard_azute/TaskBoard.WebApp/Models/Task/TaskBoardModel.cs
namespace TaskBoard.WebApp.Models.Task
{
    public class TaskBoardModel
    {
        public int Id { get; init; }

        public string Name { get; init; }
    }
}

taskboard_azute/TaskBoard.WebApp/Models/Task/TaskDetailsViewModel.cs
namespace TaskBoard.WebApp.Models.Task
{
    public class TaskDetailsViewModel : TaskViewModel
    {
        public string CreatedOn { get; init; }

        public string Board { get; init; }
    }
}

taskboard_azute/TaskBoard.WebApp/Models/Task/TaskFormModel.cs
using TaskBoard.Data;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TaskBoard.WebApp.Models.Task
{
    using static DataConstants;
    public class TaskFormModel
    {
        [Required]
        [StringLength(MaxTaskTitle, MinimumLength = MinTaskTitle,
            ErrorMessage = "Title should be at least {2} characters long.")]
        public string Title { get; set; }

        [Required]
        [StringLength(MaxTaskDescription, MinimumLength = MinTaskDescription, 
            ErrorMessage = "Description should be at least {2} characters long.")]
        public string Description { get; set; }

        [Display(Name = "Board")]
        public int BoardId { get; set; }

        public IEnumerable<TaskBoardModel> Boards { get; set; }
    }
}

taskboard_azute/TaskBoard.WebApp/Models/Task/TaskSearchFormModel.cs
using TaskBoard.Data;

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TaskBoard.WebApp.Models.Task
{
    using static DataConstants;
    public class TaskSearchFormModel
    {
        [StringLength(MaxKeyword)]
        public string Keyword { get; init; }

        public IEnumerable<TaskViewModel> Tasks { get; set; } = new List<TaskViewModel>();
    }
}

taskboard_azute/TaskBoard.WebApp/Models/Task/TaskViewModel.cs
namespace TaskBoard.WebApp.Models.Task
{
    public class TaskViewModel
    {
        public int Id { get; init; }
        public string Title { get; init; }
        public string Description { get; init; }
        public string Owner { get; init; }
    }
}

taskboard_azute/TaskBoard.WebApp/Controllers/TasksController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Globalization;
using System.Collections.Generic;

using TaskBoard.Data;
using TaskBoard.WebApp.Models.Task;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace TaskBoard.WebApp.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public TasksController(ApplicationDbContext context)
        {
            this.dbContext = context;
        }

        public IActionResult Details(int id)
        {
            var task = this.dbContext
                .Tasks
                .Where(t => t.Id == id)
                .Select(t => new TaskDetailsViewModel()
                {
                    Id = t.Id,
                    Title = t.Title,
                    Description = t.Description,
                    CreatedOn = t.CreatedOn.ToString("dd/MM/yyyy HH:mm", CultureInfo.InvariantCulture),
                    Board = t.Board.Name,
                    Owner = t.Owner.UserName
                })
                .FirstOrDefault();


            if (task == null)
            {
                return BadRequest();
            }

            return View(task);
        }

        public IActionResult Create()
        {
            TaskFormModel taskModel = new TaskFormModel()
            {
                Boards = GetBoards()
            };

            return View(taskModel);
        }

        [HttpPost]
        public IActionResult Create(TaskFormModel taskModel)
        {
            if (!GetBoards().Any(b => b.Id == taskModel.BoardId))
            {
                this.ModelState.AddModelError(nameof(taskModel.BoardId), "Board does not exist.");
            }

            if (!ModelState.IsValid)
            {
                taskModel.Boards = GetBoards();

                return View(taskModel);
            }

            string currentUserId = GetUserId();
            Task task = new Task()
            {
                Title = taskModel.Title,
                Description = taskModel.Description,
                CreatedOn = DateTime.Now,
                BoardId = taskModel.BoardId,
                OwnerId = currentUserId
            };
            this.dbContext.Tasks.Add(task);
            this.dbContext.SaveChanges();

            var boards = this.dbContext.Boards;

            return RedirectToAction("All", "Boards");
        }

        public IActionResult Edit(int id)
        {
            Task task = dbContext.Tasks.Find(id);
            if (task == null)
            {
                // When task with this id doesn't exist
                return BadRequest();
            }

            string currentUserId = GetUserId();
            if (currentUserId != task.OwnerId)
            {
                // When current user is not an owner
                return Unauthorized();
            }

            TaskFormModel taskModel = new TaskFormModel()
            {
                Title = task.Title,
                Description = task.Description,
                BoardId = task.BoardId,
                Boards = GetBoards()
            };

            return View(taskModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, TaskFormModel taskModel)
        {
            Task task = dbContext.Tasks.Find(id);
            if (task == null)
            {
                return BadRequest();
            }

            string currentUserId = GetUserId();
            if (currentUserId != task.OwnerId)
            {
                // Not an owner -> return "Unauthorized"
                return Unauthorized();
            }

            if (!GetBoards().Any(b => b.Id == taskModel.BoardId))
            {
                this.ModelState.AddModelError(nameof(taskModel.BoardId), "Board does not exist.");
            }

            if (!ModelState.IsValid)
            {
                taskModel.Boards = GetBoards();

                return View(taskModel);
            }

            task.Title = taskModel.Title;
            task.Description = taskModel.Description;
            task.BoardId = taskModel.BoardId;

            this.dbContext.SaveChanges();
            return RedirectToAction("All", "Boards");
        }

        public IActionResult Delete(int id)
        {
            Task task = dbContext.Tasks.Find(id);
            if (task == null)
            {
                // When task with this id doesn't exist
                return BadRequest();
            }

            string currentUserId = GetUserId();
            if (currentUserId != task.OwnerId)
            {
                // When current user is not an owner
                return Unauthorized();
            }

            TaskViewModel taskModel = new TaskViewModel()
            {
                Id = task.Id,
                Title = task.Title,
                Description = task.Description
            };

            return View(taskModel);
        }

        [HttpPost]
        public IActionResult Delete(TaskViewModel taskModel)
        {
            Task task = dbContext.Tasks.Find(taskModel.Id);
            if (task == null)
            {
                return BadRequest();
            }

            string currentUserId = GetUserId();
            if (currentUserId != task.OwnerId)
            {
                // Not an owner -> return "Unauthorized"
                return Unauthorized();
            }

            this.dbContext.Tasks.Remove(task);
            this.dbContext.SaveChanges();
            return RedirectToAction("All", "Boards");
        }

        public IActionResult Search()
        {
            return View(new TaskSearchFormModel());
        }

        [HttpPost]
        public IActionResult Search(TaskSearchFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var tasks = this.dbContext
                .Tasks
                .Select(t => new TaskViewModel() 
                {
                    Id = t.Id,
                    Title = t.Title,
                    Description = t.Description,
                    Owner = t.Owner.UserName
                }).ToList();

            var keyword = model.Keyword == null ? string.Empty : model.Keyword.Trim().ToLower();
            if (!String.IsNullOrEmpty(keyword) && !String.IsNullOrEmpty(keyword))
            {
                tasks = tasks
                .Where(t => t.Title.ToLower().Contains(keyword)
                    || t.Description.ToLower().Contains(keyword)).ToList();
            }

            model.Tasks = tasks;

            return View(model);
        }

        private IEnumerable<TaskBoardModel> GetBoards()
            => this.dbContext
                .Boards
                .Select(b => new TaskBoardModel()
                {
                    Id = b.Id,
                    Name = b.Name
                });

        private string GetUserId()
            => this.User.FindFirstValue(ClaimTypes.NameIdentifier);
    }
}

taskboard_azute/TaskBoard.WebApp/Views/Tasks/Create.cshtml
@model TaskFormModel

@{
    ViewBag.Title = "Create Task";
}

<link href="~/css/style.css" rel="stylesheet" type="text/css" />

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form asp-action="Create">
    @await Html.PartialAsync("_TaskFormPartial.cshtml", Model)
    <input class="btn btn-primary" type="submit" value="Create" />
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

taskboard_azute/TaskBoard.WebApp/Views/Tasks/Delete.cshtml
@model TaskViewModel

@{
    ViewData["Title"] = "Delete Task";
}

<link href="~/css/style.css" rel="stylesheet" type="text/css" />

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form asp-action="Delete">
    <table class="tasks-entry form">
        <tr>
            <th>
                <label asp-for="Title" class="control-label"></label>
            </th>
            <td>
                <input asp-for="Title" class="form-control" disabled="disabled" />
            </td>
        </tr>
        <tr>
            <th>
                <label asp-for="Description" class="control-label"></label>
            </th>
            <td>
                <textarea asp-for="Description" class="form-control" disabled="disabled"></textarea>
            </td>
        </tr>
    </table>
    <input type="submit" value="Delete" class="btn btn-primary" />
</form>



taskboard_azute/TaskBoard.WebApp/Views/Tasks/Details.cshtml
@model TaskDetailsViewModel

@{
    ViewBag.Title = "View Task Details";
}

<link href="~/css/style.css" rel="stylesheet" type="text/css" />

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<table class="task-details">
    <tr class="task-id">
        <th>ID</th>
        <td>@Model.Id</td>
    </tr>
    <tr class="title">
        <th>Title</th>
        <td>@Model.Title</td>
    </tr>
    <tr class="description">
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr class="board">
        <th>Board</th>
        <td>@Model.Board</td>
    </tr>
    <tr class="board">
        <th>Owner</th>
        <td>@Model.Owner</td>
    </tr>
    <tr class="dateCreated">
        <th>Created on</th>
        <td>@Model.CreatedOn</td>
    </tr>
    @if (Model.Owner == this.User.Identity.Name)
    {
        <tr class="actions">
            <th>Actions</th>

            <td>
                <a asp-controller="Tasks" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary">Edit</a>
                <a asp-controller="Tasks" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-secondary">Delete</a>
            </td>
        </tr>
    }
</table>

taskboard_azute/TaskBoard.WebApp/Views/Tasks/Edit.cshtml
@model TaskFormModel

@{
    ViewBag.Title = "Edit Task";
}

<link href="~/css/style.css" rel="stylesheet" type="text/css" />

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form asp-action="Edit">
    @await Html.PartialAsync("_TaskFormPartial.cshtml", Model)
    <input class="btn btn-primary" type="submit" value="Edit" />
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

taskboard_azute/TaskBoard.WebApp/Views/Tasks/Search.cshtml
@model TaskSearchFormModel

@{
    ViewBag.Title = "Search Tasks";
}

<link href="~/css/style.css" rel="stylesheet" type="text/css" />

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (Context.Request.Method == "POST")
{
    <h2>Tasks Matching Keyword "@Model.Keyword"</h2>
}

@if (Model.Tasks.Any())
{
    <h5>@Model.Tasks.Count() tasks found.</h5>
    <div class="tasks-grid">
        @await Html.PartialAsync("~/Views/Shared/_TaskPartial.cshtml", Model.Tasks)
    </div>
}
else if (Context.Request.Method == "POST")
{
    <h5>No tasks found.</h5>
}

<form asp-action="Search">
    <table class="tasks-entry form">
        <tr>
            <th>
                <label asp-for="Keyword"></label>
            </th>
            <td>
                <input asp-for="Keyword" class="form-control" placeholder="Keyword..." />
                <span asp-validation-for="Keyword" class="small text-danger"></span>
            </td>
        </tr>
    </table>
    <input class="btn btn-primary" type="submit" value="Search" />
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

taskboard_azute/TaskBoard.WebApp/Views/Tasks/_TaskFormPartial.cshtml
@model TaskFormModel

<table class="tasks-entry form">
    <tr>
        <th>
            <label asp-for="Title"></label>
        </th>
        <td>
            <input asp-for="Title" class="form-control" placeholder="Title...">
            <span asp-validation-for="Title" class="small text-danger"></span>
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="Description"></label>
        </th>
        <td>
            <textarea asp-for="Description" class="form-control" placeholder="Description..."></textarea>
            <span asp-validation-for="Description" class="small text-danger"></span>
        </td>
    </tr>
    <tr>
        <th>
            <label asp-for="BoardId"></label>
        </th>
        <td>
            <select asp-for="BoardId" class="form-control">
                @foreach (var tag in Model.Boards)
                {
                    <option value="@tag.Id">@tag.Name</option>
                }
            </select>
            <span asp-validation-for="BoardId" class="small text-danger"></span>
        </td>
    </tr>
</table>